_: {
  projectRootFile = "flake.nix";
  programs.alejandra.enable = true;
  programs.statix.enable = true;
  programs.deadnix.enable = true;
  # generated by nixos-generate-config; keep byte-identical
  settings.global.excludes = ["hosts/*/hardware-configuration.nix"];
}
